sudo: required

services:
  - docker

git:
  depth: 5

addons:
  apt:
    packages:
      # 7z is used for packaging (see before_deploy)
      - p7zip-full

env:
  global:
  - ONECVERSION=8.3.10.2639
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/docker'
    - '$TRAVIS_BUILD_DIR/build'

before_install:
  - sudo ./tools/linux/dockerdownload.sh
  - docker images | grep onec

#install:
#  - docker pull evilbeaver/onescript:1.0.19

jobs:
  include:
  - stage: compile
    script:
      - sudo docker run --detach -e XVFB_RESOLUTION=1920x1080x24 --volume="${PWD}":/home/ubuntu/code onec32/client:${ONECVERSION} client > /tmp/container_id
      - sudo docker ps && sleep 5
      - sudo docker exec -u ubuntu "$(cat /tmp/container_id)" /bin/bash -c "cd /home/ubuntu/code; DISPLAY=:1.0 wget -q --continue -O /tmp/oscript.deb http://oscript.io/downloads/night-build/onescript-engine_1.0.20_all.deb  && sudo dpkg -i /tmp/oscript.deb"
      - sudo docker exec -u ubuntu "$(cat /tmp/container_id)" /bin/bash -c "cd /home/ubuntu/code; DISPLAY=:1.0 sudo opm install && sudo opm update -all"
      - sudo docker exec -u ubuntu "$(cat /tmp/container_id)" /bin/bash -c "cd /home/ubuntu/code; DISPLAY=:1.0 sudo opm run init file --buildFolderPath ./build"
      - sudo docker stop "$(cat /tmp/container_id)"

  - stage: test
    script:
      - sudo docker run --detach -e XVFB_RESOLUTION=1920x1080x24 --volume="${PWD}":/home/ubuntu/code onec32/client:${ONECVERSION} client > /tmp/container_id
      - sudo docker ps && sleep 5
      - sudo docker run -d -p 4040:4040 --link "$(cat /tmp/container_id)":http wernight/ngrok ngrok http http:6080 > /tmp/container_idngrok
      - sleep 5 && echo $(curl -s http://127.0.0.1:4040/status | grep -P "http://.*?ngrok.io" -oh)"/vnc_auto.html"
      - sudo docker exec -u ubuntu "$(cat /tmp/container_id)" /bin/bash -c "cd /home/ubuntu/code; DISPLAY=:1.0 wget -q --continue -O /tmp/oscript.deb http://oscript.io/downloads/night-build/onescript-engine_1.0.20_all.deb  && sudo dpkg -i /tmp/oscript.deb"
      - sudo docker exec -u ubuntu "$(cat /tmp/container_id)" /bin/bash -c "cd /home/ubuntu/code; DISPLAY=:1.0 sudo opm install && sudo opm update -all"
      - sudo docker exec -u ubuntu "$(cat /tmp/container_id)" /bin/bash -c "cd /home/ubuntu/code; DISPLAY=:1.0 sudo opm run vanessa all --path ./build/feature/StepsRunner/ --settings ./tools/JSON/VBParams8310UF.json"
      - sudo docker stop "$(cat /tmp/container_id)"
      - sudo docker stop "$(cat /tmp/container_idngrok )"

  - stage: test
    script:
      - sudo docker run --detach -e XVFB_RESOLUTION=1920x1080x24 --volume="${PWD}":/home/ubuntu/code onec32/client:${ONECVERSION} client > /tmp/container_id
      - sudo docker ps && sleep 5
      - sudo docker run -d -p 4040:4040 --link "$(cat /tmp/container_id)":http wernight/ngrok ngrok http http:6080 > /tmp/container_idngrok
      - sleep 5 && echo $(curl -s http://127.0.0.1:4040/status | grep -P "http://.*?ngrok.io" -oh)"/vnc_auto.html"
      - sudo docker exec -u ubuntu "$(cat /tmp/container_id)" /bin/bash -c "cd /home/ubuntu/code; DISPLAY=:1.0 wget -q --continue -O /tmp/oscript.deb http://oscript.io/downloads/night-build/onescript-engine_1.0.20_all.deb  && sudo dpkg -i /tmp/oscript.deb"
      - sudo docker exec -u ubuntu "$(cat /tmp/container_id)" /bin/bash -c "cd /home/ubuntu/code; DISPLAY=:1.0 sudo opm install && sudo opm update -all"
      - sudo docker exec -u ubuntu "$(cat /tmp/container_id)" /bin/bash -c "cd /home/ubuntu/code; DISPLAY=:1.0 sudo opm run vanessa all --path ./build/feature/StepsProgramming/ --settings ./tools/JSON/VBParams8310UF.json"
      - sudo docker stop "$(cat /tmp/container_id)"
      - sudo docker stop "$(cat /tmp/container_idngrok )"

  - stage: clean
    script: sudo rm -rf ./build/ib && sudo rm -rf ./build/ibservice && rm -rf ./build/ServiceBases

        

#notifications:
#  email: true

# deploy:
#   - provider: releases
#     api_key:
#       secure: "$GITHUB_OAUTH_TOKEN"
#     file:
#       - "add.tar.gz"
#       - "add.7z"
#       - "add-*.ospx"
#       - "add.tar.bz2"
#     file_glob: "true" 
#     skip_cleanup: true
#     on:
#       tags: true
#       branch: master
  
#   - provider: script
#     skip_cleanup: true
#     script: docker run -it -v $(pwd):/work_dir evilbeaver/onescript:1.0.19 sh -c 'cd /work_dir; opm push --token $GITHUB_OAUTH_TOKEN --channel dev --file ./add-*.ospx; exit'
#     on:
#       branch: develop
#   - provider: script
#     skip_cleanup: true
#     script: docker run -it -v $(pwd):/work_dir evilbeaver/onescript:1.0.19 sh -c 'cd /work_dir; opm push --token $GITHUB_OAUTH_TOKEN --channel stable --file ./add-*.ospx; exit'
#     on:
#       branch: master
#       tags: true